CREATE DATABASE west;
CREATE TABLE `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) DEFAULT NULL,
  `password` VARCHAR(32) DEFAULT NULL,
  `countSize` VARCHAR(20) DEFAULT '0.0B',
  `totalSize` VARCHAR(20) DEFAULT '10.0GB',
   registerTime VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `file` (
  `fileId` INT(11) NOT NULL AUTO_INCREMENT,
  fileName VARCHAR(255) DEFAULT NULL,
  `userName` VARCHAR(255) DEFAULT NULL,
  fileType VARCHAR(255) DEFAULT NULL,
  fileSize VARCHAR(50) DEFAULT NULL,
  lastTime DATETIME,
  url VARCHAR(255) DEFAULT NULL,
  `filePath` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`fileId`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
